CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, email text NOT NULL UNIQUE, password_hash text NOT NULL, role text NOT NULL DEFAULT 'sales' CHECK(role IN ('super_admin','admin','sales')), active boolean NOT NULL DEFAULT true, session_version integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE users ADD COLUMN IF NOT EXISTS session_version integer NOT NULL DEFAULT 0;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('super_admin','admin','sales'));
CREATE TABLE IF NOT EXISTS companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, website text, industry text, phone text, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE SET NULL, first_name text NOT NULL, last_name text, email text UNIQUE, phone text, line_user_id text UNIQUE, title text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS leads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, company_id uuid REFERENCES companies(id) ON DELETE SET NULL, contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL, owner_id uuid NOT NULL REFERENCES users(id), stage text NOT NULL DEFAULT 'New' CHECK(stage IN ('New','Qualified','Proposal','Won','Lost')), source text NOT NULL DEFAULT 'Manual', value numeric(14,2), probability integer NOT NULL DEFAULT 0 CHECK(probability BETWEEN 0 AND 100), next_follow_up timestamptz, loss_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS leads_stage_idx ON leads(stage); CREATE INDEX IF NOT EXISTS leads_owner_idx ON leads(owner_id); CREATE INDEX IF NOT EXISTS leads_updated_idx ON leads(updated_at DESC);
CREATE INDEX IF NOT EXISTS leads_company_id_idx ON leads(company_id); CREATE INDEX IF NOT EXISTS leads_contact_id_idx ON leads(contact_id);
CREATE TABLE IF NOT EXISTS activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE, actor_id uuid REFERENCES users(id) ON DELETE SET NULL, type text NOT NULL, body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS activities_actor_id_idx ON activities(actor_id); CREATE INDEX IF NOT EXISTS activities_lead_id_idx ON activities(lead_id);
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid REFERENCES leads(id) ON DELETE SET NULL, contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL, channel text NOT NULL DEFAULT 'LINE', direction text NOT NULL CHECK(direction IN ('inbound','outbound')), content text NOT NULL, status text NOT NULL DEFAULT 'received' CHECK(status IN ('received','draft','approved','queued','sent','failed')), external_id text, created_by uuid REFERENCES users(id) ON DELETE SET NULL, approved_by uuid REFERENCES users(id) ON DELETE SET NULL, sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS messages_contact_idx ON messages(contact_id, created_at DESC);
CREATE INDEX IF NOT EXISTS messages_approved_by_idx ON messages(approved_by); CREATE INDEX IF NOT EXISTS messages_created_by_idx ON messages(created_by); CREATE INDEX IF NOT EXISTS messages_lead_id_idx ON messages(lead_id);
CREATE TABLE IF NOT EXISTS webhook_events (event_key text PRIMARY KEY, line_user_id text, payload jsonb NOT NULL, processed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_suggestions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE, kind text NOT NULL, result jsonb NOT NULL, provider text NOT NULL, status text NOT NULL DEFAULT 'suggested' CHECK(status IN ('suggested','accepted','dismissed')), created_by uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ai_suggestions_created_by_idx ON ai_suggestions(created_by); CREATE INDEX IF NOT EXISTS ai_suggestions_lead_id_idx ON ai_suggestions(lead_id);
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES users(id) ON DELETE SET NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_logs_actor_id_idx ON audit_logs(actor_id);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
