import './environment.js';
import express from 'express';
import cors from 'cors';
import pino from 'pino';
import { pinoHttp } from 'pino-http';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { query, pool } from './db/pool.js';
import { databaseErrorCode } from './db/config.js';
import { issueToken, requireAuth, validateJwtSecret } from './auth.js';
import { createAIRouter } from './ai-routes.js';
import { sendLineText } from './line.js';
import { createLineWebhookRouter } from './line-webhook.js';
import { createContactsLineRouter } from './contacts-line.js';
import { createRecordRouter } from './record-routes.js';
import { currentSession, resourceAccess, leadScope, isSuperAdmin, messageScopeSql } from './access.js';
import { createMemberRouter } from './member-routes.js';
import { createFollowUpRouter } from './follow-up-routes.js';

validateJwtSecret();
const app=express(); const logger=pino({level:process.env.LOG_LEVEL||'info'});
app.use(cors({origin:process.env.WEB_ORIGIN||'http://localhost:3000'}));
app.use(pinoHttp({logger,serializers:{req:req=>({id:req.id,method:req.method,url:req.url?.split('?')[0]})}}));
app.use(createLineWebhookRouter(pool));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',async(req,res)=>{
  res.set('Cache-Control','no-store');
  try {
    await query('SELECT 1');
    res.json({status:'ok',database:'ok',lineConfigured:Boolean(process.env.LINE_CHANNEL_ACCESS_TOKEN)});
  } catch(error) {
    req.log.error({event:'database_health_failed',code:databaseErrorCode(error)},'Database health check failed');
    res.status(503).json({status:'degraded',database:'unavailable'});
  }
});
app.post('/api/auth/login',async(req,res)=>{const parsed=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid login data'});const {email,password}=parsed.data;const r=await query('SELECT id,name,email,password_hash,role,session_version FROM users WHERE lower(email)=lower($1) AND active=true',[email]);const u=r.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Email or password is incorrect'});const user={id:u.id,name:u.name,email:u.email,role:u.role,session_version:u.session_version};res.json({token:issueToken(user),user});});
app.use('/api',requireAuth,currentSession({query}),resourceAccess({query}));
app.use('/api',createMemberRouter({query}));
app.use('/api',createFollowUpRouter({query}));
app.use('/api',createRecordRouter(pool));
app.get('/api/me',(req,res)=>res.json({user:req.user}));
app.get('/api/dashboard',async(req,res)=>{const [stages,follow,latest]=await Promise.all([query('SELECT stage,count(*)::int count FROM leads WHERE ($1::boolean OR owner_id=$2) GROUP BY stage',leadScope(req)),query("SELECT count(*)::int count FROM leads WHERE ($1::boolean OR owner_id=$2) AND next_follow_up<=now() AND stage NOT IN ('Won','Lost')",leadScope(req)),query(`SELECT l.id,l.title,l.stage,l.updated_at,c.name company FROM leads l LEFT JOIN companies c ON c.id=l.company_id WHERE ($1::boolean OR l.owner_id=$2) ORDER BY l.updated_at DESC LIMIT 6`,leadScope(req))]);res.json({stages:stages.rows,followUpDue:follow.rows[0].count,recent:latest.rows});});
app.get('/api/leads',async(req,res)=>{const q=String(req.query.q||'').trim();const stage=String(req.query.stage||'');const params:any[]=leadScope(req);let where='WHERE ($1::boolean OR l.owner_id=$2)';if(q){params.push(`%${q}%`);where+=` AND (l.title ILIKE $${params.length} OR c.name ILIKE $${params.length} OR ct.first_name ILIKE $${params.length} OR ct.last_name ILIKE $${params.length})`;}if(stage&&['New','Qualified','Proposal','Won','Lost'].includes(stage)){params.push(stage);where+=` AND l.stage=$${params.length}`;}params.push(Math.min(Number(req.query.limit)||300,500));const r=await query(`SELECT l.*,c.name company,ct.first_name contact_first,ct.last_name contact_last,u.name owner FROM leads l LEFT JOIN companies c ON c.id=l.company_id LEFT JOIN contacts ct ON ct.id=l.contact_id JOIN users u ON u.id=l.owner_id ${where} ORDER BY l.updated_at DESC LIMIT $${params.length}`,params);res.json({items:r.rows});});
app.post('/api/leads',async(req,res)=>{const p=z.object({title:z.string().min(2),companyId:z.string().uuid().optional().nullable(),contactId:z.string().uuid().optional().nullable(),stage:z.enum(['New','Qualified','Proposal','Won','Lost']).default('New'),source:z.string().default('Manual'),ownerId:z.string().uuid().optional(),value:z.number().nonnegative().optional().nullable()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid lead',details:p.error.flatten()});const x=p.data;if(x.ownerId&&!isSuperAdmin(req.user)&&x.ownerId!==req.user!.id)return res.status(403).json({error:'Cannot assign another member'});const owner=x.ownerId||req.user!.id;if(!(await query('SELECT id FROM users WHERE id=$1 AND active=true',[owner])).rows.length)return res.status(400).json({error:'Owner must be an active member'});const r=await query(`INSERT INTO leads(title,company_id,contact_id,owner_id,stage,source,value) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[x.title,x.companyId||null,x.contactId||null,owner,x.stage,x.source,x.value??null]);await query(`INSERT INTO activities(lead_id,actor_id,type,body) VALUES($1,$2,'created','Lead created')`,[r.rows[0].id,req.user!.id]);await audit(req.user!.id,'lead.created','lead',r.rows[0].id,{});res.status(201).json({item:r.rows[0]});});
app.get('/api/leads/:id',async(req,res)=>{const lead=await query(`SELECT l.*,c.name company,c.website,ct.first_name,ct.last_name,ct.email,ct.phone,ct.line_user_id,u.name owner FROM leads l LEFT JOIN companies c ON c.id=l.company_id LEFT JOIN contacts ct ON ct.id=l.contact_id JOIN users u ON u.id=l.owner_id WHERE l.id=$1 AND ($2::boolean OR l.owner_id=$3)`,[req.params.id,...leadScope(req)]);if(!lead.rowCount)return res.status(404).json({error:'Lead not found'});const [activities,messages,suggestions]=await Promise.all([query('SELECT a.*,u.name actor FROM activities a LEFT JOIN users u ON u.id=a.actor_id WHERE lead_id=$1 ORDER BY created_at DESC',[req.params.id]),query(`SELECT * FROM messages WHERE (lead_id=$1 OR contact_id=$2) AND ($3::boolean OR ${messageScopeSql}) ORDER BY created_at DESC`,[req.params.id,lead.rows[0].contact_id,...leadScope(req)]),query('SELECT * FROM ai_suggestions WHERE lead_id=$1 ORDER BY created_at DESC LIMIT 5',[req.params.id])]);res.json({lead:lead.rows[0],activities:activities.rows,messages:messages.rows,suggestions:suggestions.rows});});
app.patch('/api/leads/:id/stage',async(req,res)=>{const p=z.object({stage:z.enum(['New','Qualified','Proposal','Won','Lost']),lossReason:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid stage'});const old=await query('SELECT stage FROM leads WHERE id=$1 AND ($2::boolean OR owner_id=$3)',[req.params.id,...leadScope(req)]);if(!old.rowCount)return res.status(404).json({error:'Lead not found'});const r=await query('UPDATE leads SET stage=$1,loss_reason=$2,updated_at=now() WHERE id=$3 AND ($4::boolean OR owner_id=$5) RETURNING *',[p.data.stage,p.data.lossReason||null,req.params.id,...leadScope(req)]);await query('INSERT INTO activities(lead_id,actor_id,type,body) VALUES($1,$2,\'stage_changed\',$3)',[req.params.id,req.user!.id,`${old.rows[0].stage} → ${p.data.stage}`]);await audit(req.user!.id,'lead.stage_changed','lead',req.params.id,{from:old.rows[0].stage,to:p.data.stage});res.json({item:r.rows[0]});});
app.post('/api/leads/:id/activities',async(req,res)=>{const p=z.object({type:z.string().min(2),body:z.string().min(1)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid activity'});const r=await query('INSERT INTO activities(lead_id,actor_id,type,body) SELECT $1,$2,$3,$4 FROM leads WHERE id=$1 AND ($5::boolean OR owner_id=$6) RETURNING *',[req.params.id,req.user!.id,p.data.type,p.data.body,...leadScope(req)]);res.status(201).json({item:r.rows[0]});});
app.use('/api',createAIRouter({query}));
app.post('/api/leads/:id/messages/drafts',async(req,res)=>{const p=z.object({content:z.string().min(1),contactId:z.string().uuid().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid draft'});const lead=await query('SELECT contact_id FROM leads WHERE id=$1 AND ($2::boolean OR owner_id=$3)',[req.params.id,...leadScope(req)]);if(!lead.rowCount)return res.status(404).json({error:'Lead not found'});if(p.data.contactId&&p.data.contactId!==lead.rows[0].contact_id)return res.status(400).json({error:'Contact must match the lead'});const r=await query(`INSERT INTO messages(lead_id,contact_id,channel,direction,content,status,created_by) VALUES($1,$2,'LINE','outbound',$3,'draft',$4) RETURNING *`,[req.params.id,p.data.contactId||lead.rows[0].contact_id,p.data.content,req.user!.id]);await audit(req.user!.id,'message.drafted','message',r.rows[0].id,{});res.status(201).json({item:r.rows[0]});});
app.post('/api/messages/:id/approve',async(req,res)=>{const r=await query(`UPDATE messages SET status='approved',approved_by=$1 WHERE id=$2 AND status='draft' AND ($3::boolean OR lead_id IN (SELECT id FROM leads WHERE owner_id=$4)) RETURNING *`,[req.user!.id,req.params.id,...leadScope(req)]);if(!r.rowCount)return res.status(409).json({error:'Message is not in draft status'});await audit(req.user!.id,'message.approved','message',req.params.id,{});res.json({item:r.rows[0]});});
app.post('/api/messages/:id/send',async(req,res)=>{const r=await query(`SELECT m.*,c.line_user_id FROM messages m LEFT JOIN contacts c ON c.id=m.contact_id WHERE m.id=$1 AND m.status IN ('approved','failed') AND m.approved_by IS NOT NULL AND ($2::boolean OR m.lead_id IN (SELECT id FROM leads WHERE owner_id=$3))`,[req.params.id,...leadScope(req)]);if(!r.rowCount)return res.status(409).json({error:'Message must be approved before sending'});if(!r.rows[0].line_user_id)return res.status(422).json({error:'Contact has no linked LINE user'});try{const externalId=await sendLineText(r.rows[0].line_user_id,r.rows[0].content);const sent=await query(`UPDATE messages SET status='sent',sent_at=now(),external_id=coalesce($1,external_id) WHERE id=$2 RETURNING *`,[externalId,req.params.id]);await audit(req.user!.id,'message.sent','message',req.params.id,{});res.json({item:sent.rows[0]});}catch(e){await query(`UPDATE messages SET status='failed' WHERE id=$1`,[req.params.id]);res.status(503).json({error:'LINE unavailable; message saved as failed and can be retried after approval'});}});
app.use('/api',createContactsLineRouter({query}));
app.get('/api/contacts/:id',async(req,res)=>{const contact=await query('SELECT ct.*,c.name company FROM contacts ct LEFT JOIN companies c ON c.id=ct.company_id WHERE ct.id=$1',[req.params.id]);if(!contact.rowCount)return res.status(404).json({error:'Contact not found'});const [leads,messages]=await Promise.all([query('SELECT id,title,stage,source,value,updated_at FROM leads WHERE contact_id=$1 AND ($2::boolean OR owner_id=$3) ORDER BY updated_at DESC LIMIT 500',[req.params.id,...leadScope(req)]),query(`SELECT id,content,direction,status,created_at FROM messages WHERE contact_id=$1 AND ($2::boolean OR lead_id IN (SELECT id FROM leads WHERE owner_id=$3) OR (lead_id IS NULL AND contact_id IN (SELECT contact_id FROM leads WHERE owner_id=$3))) ORDER BY created_at DESC,id DESC LIMIT 100`,[req.params.id,...leadScope(req)])]);res.json({contact:contact.rows[0],leads:leads.rows,messages:messages.rows});});
app.post('/api/contacts',async(req,res)=>{const p=z.object({firstName:z.string().min(1),lastName:z.string().optional(),email:z.string().email().optional().or(z.literal('')),phone:z.string().optional(),companyId:z.string().uuid().optional().nullable(),title:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid contact',details:p.error.flatten()});try{const x=p.data;const r=await query('INSERT INTO contacts(first_name,last_name,email,phone,company_id,title) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[x.firstName,x.lastName||null,x.email||null,x.phone||null,x.companyId||null,x.title||null]);res.status(201).json({item:r.rows[0]});}catch{res.status(409).json({error:'Contact could not be created; check for duplicate email'});}});
app.get('/api/companies',async(req,res)=>{const r=await query('SELECT c.*,count(DISTINCT ct.id)::int contact_count,count(DISTINCT l.id)::int lead_count FROM companies c LEFT JOIN contacts ct ON ct.company_id=c.id LEFT JOIN leads l ON l.company_id=c.id AND ($1::boolean OR l.owner_id=$2) GROUP BY c.id ORDER BY c.name LIMIT 200',leadScope(req));res.json({items:r.rows});});
app.get('/api/companies/:id',async(req,res)=>{const company=await query('SELECT * FROM companies WHERE id=$1',[req.params.id]);if(!company.rowCount)return res.status(404).json({error:'Company not found'});const [contacts,leads]=await Promise.all([query('SELECT id,first_name,last_name,email,phone,title,line_user_id FROM contacts WHERE company_id=$1 ORDER BY first_name,last_name LIMIT 500',[req.params.id]),query(`SELECT l.id,l.title,l.stage,l.source,l.value,l.updated_at,concat_ws(' ',ct.first_name,ct.last_name) contact_name,u.name owner FROM leads l LEFT JOIN contacts ct ON ct.id=l.contact_id LEFT JOIN users u ON u.id=l.owner_id WHERE l.company_id=$1 AND ($2::boolean OR l.owner_id=$3) ORDER BY l.updated_at DESC LIMIT 500`,[req.params.id,...leadScope(req)])]);res.json({company:company.rows[0],contacts:contacts.rows,leads:leads.rows});});
app.post('/api/companies',async(req,res)=>{const p=z.object({name:z.string().min(2),website:z.string().optional(),industry:z.string().optional(),phone:z.string().optional(),notes:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid company',details:p.error.flatten()});const x=p.data;const r=await query('INSERT INTO companies(name,website,industry,phone,notes) VALUES($1,$2,$3,$4,$5) RETURNING *',[x.name,x.website||null,x.industry||null,x.phone||null,x.notes||null]);res.status(201).json({item:r.rows[0]});});
app.post('/api/contacts/:id/link-line',async(req,res)=>{const p=z.object({lineUserId:z.string().min(5)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid LINE user ID'});try{const r=await query('UPDATE contacts SET line_user_id=$1,updated_at=now() WHERE id=$2 RETURNING *',[p.data.lineUserId,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Contact not found'});await query('UPDATE messages SET contact_id=$1 WHERE contact_id IS NULL AND external_id IN (SELECT payload->\'message\'->>\'id\' FROM webhook_events WHERE line_user_id=$2)',[req.params.id,p.data.lineUserId]);res.json({item:r.rows[0]});}catch{res.status(409).json({error:'LINE user is already linked to another contact'});}});
async function audit(actor:string,action:string,type:string,id:string,details:object){await query('INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5)',[actor,action,type,id,details]);}
if (process.env.VERCEL !== '1') {
  const port=Number(process.env.PORT||4000);const server=app.listen(port,()=>logger.info({port},'CRM API listening'));
  process.on('SIGTERM',()=>server.close(()=>pool.end()));
}
export default app;
